twig:
    file_name_pattern: '*.twig'
    globals:
        app_env: '%app.environment%'
        settings: '@App\Service\SettingsService'
    form_themes:
        - 'forms/form_row.html.twig'
when@test:
    twig:
        strict_variables: true
